Incolab\ForumBundle\Entity\ForumRole:
    type: entity
    table: null
    repositoryClass: Incolab\ForumBundle\Repository\ForumRoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
