Incolab\ForumBundle\Entity\Post:
    type: entity
    table: forum_post
    repositoryClass: Incolab\ForumBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: text
        createdAt:
            type: datetime
            column: createdat
        updatedAt:
            type: datetime
            column: updatedat
            nullable: true
    manyToOne:
        topic:
            targetEntity: Incolab\ForumBundle\Entity\Topic
            cascade: ["persist"]
            inversedBy: replies
            joinColumn:
                onDelete: CASCADE
        author:
            targetEntity: UserBundle\Entity\User
            
    lifecycleCallbacks: {  }
