services:
    incolab_forum.category_manager:
        class: Incolab\ForumBundle\Model\CategoryManager
        arguments:
            $transliterator: "@incolab_core.transliterator"
            $database: "@db"
            
    incolab_forum.topic_manager:
        class: Incolab\ForumBundle\Model\TopicManager
        arguments:
            $transliterator: "@incolab_core.transliterator"
            $database: "@db"
            
    incolab_forum.post_manager:
        class: Incolab\ForumBundle\Model\PostManager
        arguments:
            $database: "@db"
#    incolab_forum.example:
#        class: Incolab\ForumBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
