<?php

namespace Incolab\ForumBundle\Repository;

/**
 * ForumRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
