<?php

namespace Incolab\ForumBundle\Repository;

use UserBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public static $strPostForEditQuery = "SELECT p, "
            . "partial t.{id, slug}, partial c.{id, slug}, partial q.{id, slug} "
            . "FROM IncolabForumBundle:Post p "
            . "LEFT JOIN p.topic t LEFT JOIN t.category c LEFT JOIN c.parent q "
            . "WHERE p.id = :id AND p.author = :author AND t.slug = :slugTopic "
            . "AND c.slug = :slugCat AND q.slug = :slugParentCat";
    
    public function getPostForEdit($slugParentCat, $slugCat, $slugTopic, $postId, User $author)
    {
        $parameters = array(
            ':id' => $postId,
            ':author' => $author,
            ':slugTopic' => $slugTopic,
            ':slugCat' => $slugCat,
            ':slugParentCat' => $slugParentCat
        );
        
        $query = $this->_em->createQuery(self::$strPostForEditQuery)
                ->setParameters($parameters);
        return $query->getOneOrNullResult();
    }
}
